proj::selekcjanatur::Czlowiek
int proj.selekcjanatur.Czlowiek.x
Pozycja x na planszy.
Referenced by proj.selekcjanatur.Symulacja.aktualizujStan, proj.selekcjanatur.Czlowiek.Czlowiek, proj.selekcjanatur.Symulacja.dodajLosowychLudzi, proj.selekcjanatur.Kobieta.Kobieta, proj.selekcjanatur.Mezczyzna.Mezczyzna, proj.selekcjanatur.Symulacja.przemiescSieNaPole, proj.selekcjanatur.Czlowiek.rozmnazajZ, proj.selekcjanatur.Symulacja.wykonajRuch, proj.selekcjanatur.Symulacja.znajdzNajblizszeJedzenie, proj.selekcjanatur.Symulacja.znajdzPartnera.
int proj.selekcjanatur.Czlowiek.y
Pozycja y na planszy.
Referenced by proj.selekcjanatur.Symulacja.aktualizujStan, proj.selekcjanatur.Czlowiek.Czlowiek, proj.selekcjanatur.Symulacja.dodajLosowychLudzi, proj.selekcjanatur.Kobieta.Kobieta, proj.selekcjanatur.Mezczyzna.Mezczyzna, proj.selekcjanatur.Symulacja.przemiescSieNaPole, proj.selekcjanatur.Czlowiek.rozmnazajZ, proj.selekcjanatur.Symulacja.wykonajRuch, proj.selekcjanatur.Symulacja.znajdzNajblizszeJedzenie, proj.selekcjanatur.Symulacja.znajdzPartnera.
final int proj.selekcjanatur.Czlowiek.id
Unikalny identyfikator człowieka.
Referenced by proj.selekcjanatur.Czlowiek.toString.
boolean proj.selekcjanatur.Czlowiek.zywy
Flaga określająca czy człowiek jest żywy.
Referenced by proj.selekcjanatur.Czlowiek.aktualizuj, proj.selekcjanatur.Symulacja.aktualizujStan, proj.selekcjanatur.Symulacja.znajdzPartnera.
float proj.selekcjanatur.Czlowiek.poziomGlodu
Poziom głodu (0-100)
Referenced by proj.selekcjanatur.Czlowiek.aktualizuj, proj.selekcjanatur.Kobieta.mozeRozmnazac, proj.selekcjanatur.Mezczyzna.mozeRozmnazac, proj.selekcjanatur.Czlowiek.zjedz.
int proj.selekcjanatur.Czlowiek.czasOdRozmnazania
Liczba cykli od ostatniego rozmnożenia.
Referenced by proj.selekcjanatur.Czlowiek.aktualizuj, proj.selekcjanatur.Kobieta.mozeRozmnazac, proj.selekcjanatur.Mezczyzna.mozeRozmnazac.
Gen [] proj.selekcjanatur.Czlowiek.geny
Tablica genów człowieka (wzrok, prędkość, metabolizm)
Referenced by proj.selekcjanatur.Kobieta.Kobieta, proj.selekcjanatur.Czlowiek.predkosc, proj.selekcjanatur.Czlowiek.rozmnazajZ, proj.selekcjanatur.Czlowiek.zasiegWzroku, proj.selekcjanatur.Czlowiek.zuzycieEnergii.
int proj.selekcjanatur.Czlowiek.wiek
Wiek człowieka w cyklach symulacji.
Referenced by proj.selekcjanatur.Czlowiek.aktualizuj, proj.selekcjanatur.Symulacja.aktualizujStan, proj.selekcjanatur.Czlowiek.czyUmieraZeStarosci, proj.selekcjanatur.Symulacja.dodajLosowychLudzi, proj.selekcjanatur.Czlowiek.jestDzieckiem.
int proj.selekcjanatur.Czlowiek.globalneId
Licznik globalny do generowania unikalnych ID.
Referenced by proj.selekcjanatur.Czlowiek.Czlowiek.
proj.selekcjanatur.Czlowiek.Czlowiek(int x, int y)
Konstruktor tworzący nowego człowieka.
x Pozycja startowa x y Pozycja startowa y
References proj.selekcjanatur.Czlowiek.globalneId, proj.selekcjanatur.Czlowiek.x, proj.selekcjanatur.Czlowiek.y.
Referenced by proj.selekcjanatur.Czlowiek.rozmnazajZ.
boolean proj.selekcjanatur.Czlowiek.jestDzieckiem()
Sprawdza czy człowiek jest dzieckiem.
true jeśli wiek < 18 cykli
References proj.selekcjanatur.Czlowiek.wiek.
Referenced by proj.selekcjanatur.Kobieta.mozeRozmnazac, proj.selekcjanatur.Mezczyzna.mozeRozmnazac.
int proj.selekcjanatur.Czlowiek.zasiegWzroku()
Oblicza zasięg wzroku na podstawie genów.
Zasięg wzroku w komórkach
References proj.selekcjanatur.Czlowiek.geny.
Referenced by proj.selekcjanatur.Symulacja.znajdzNajblizszeJedzenie, proj.selekcjanatur.Symulacja.znajdzPartnera.
int proj.selekcjanatur.Czlowiek.predkosc()
Oblicza prędkość poruszania na podstawie genów.
Prędkość (1-3)
References proj.selekcjanatur.Czlowiek.geny.
Referenced by proj.selekcjanatur.Czlowiek.powinnienSieRuszyc.
float proj.selekcjanatur.Czlowiek.zuzycieEnergii()
Oblicza zużycie energii na cykl.
Wartość zużycia energii
References proj.selekcjanatur.Czlowiek.geny.
Referenced by proj.selekcjanatur.Czlowiek.aktualizuj.
void proj.selekcjanatur.Czlowiek.aktualizuj()
Aktualizuje stan człowieka w każdym cyklu symulacji.
Zwiększa wiek, zmniejsza poziom energii, sprawdza warunki śmierci z głodu i starości
References proj.selekcjanatur.Czlowiek.czasOdRozmnazania, proj.selekcjanatur.Czlowiek.czyUmieraZeStarosci, proj.selekcjanatur.Czlowiek.poziomGlodu, proj.selekcjanatur.Czlowiek.wiek, proj.selekcjanatur.Czlowiek.zuzycieEnergii, proj.selekcjanatur.Czlowiek.zywy.
boolean proj.selekcjanatur.Czlowiek.powinnienSieRuszyc(int klatki)
Decyduje czy człowiek powinien się poruszyć w danej klatce.
klatki Numer klatki symulacji true jeśli powinien się poruszyć
References proj.selekcjanatur.Czlowiek.predkosc.
abstract boolean proj.selekcjanatur.Czlowiek.mozeRozmnazac()
Sprawdza możliwość rozmnożenia.
true jeśli może się rozmnożyć
Referenced by proj.selekcjanatur.Symulacja.aktualizujStan.
void proj.selekcjanatur.Czlowiek.zjedz(Jedzenie jedzenie)
Zjada podane jedzenie.
jedzenie Obiekt jedzenia do spożycia
References proj.selekcjanatur.Czlowiek.poziomGlodu, proj.selekcjanatur.Jedzenie.wartosc.
Referenced by proj.selekcjanatur.Symulacja.przemiescSieNaPole.
abstract boolean proj.selekcjanatur.Czlowiek.czyMezczyzna()
Sprawdza płeć człowieka.
true jeśli to mężczyzna
Referenced by proj.selekcjanatur.Symulacja.aktualizujStan, proj.selekcjanatur.Symulacja.dodajLosowychLudzi, proj.selekcjanatur.Symulacja.znajdzPartnera.
boolean proj.selekcjanatur.Czlowiek.czyUmieraZeStarosci()
Sprawdza czy człowiek umiera ze starości.
true jeśli umiera Szansa rośnie liniowo od wieku 70 cykli: 70 cykli: 0% szansy 100 cykli: 30% szansy 170 cykli: 100% szansy
References proj.selekcjanatur.App.random, proj.selekcjanatur.Czlowiek.wiek.
Referenced by proj.selekcjanatur.Czlowiek.aktualizuj.
Czlowiek proj.selekcjanatur.Czlowiek.rozmnazajZ(Czlowiek inny)
Rozmnaża się z innym człowiekiem.
inny Drugi rodzic Nowy człowiek (dziecko) Dziecko dziedziczy losowo geny od rodziców, powstaje w pozycji pierwszego rodzica
References proj.selekcjanatur.Czlowiek.Czlowiek, proj.selekcjanatur.Czlowiek.geny, proj.selekcjanatur.Gen.odziedzicz, proj.selekcjanatur.App.random, proj.selekcjanatur.Czlowiek.x, proj.selekcjanatur.Czlowiek.y.
Referenced by proj.selekcjanatur.Symulacja.aktualizujStan.
String proj.selekcjanatur.Czlowiek.toString()
Reprezentacja tekstowa człowieka.
String w formacie "Klasa@ID"
References proj.selekcjanatur.Czlowiek.id.