proj::selekcjanatur::SymulacjaPlik
final List<String> proj.selekcjanatur.SymulacjaPlik.zdarzenia
Lista wczytanych zdarzeń z pliku.
Referenced by proj.selekcjanatur.SymulacjaPlik.aktualizuj, proj.selekcjanatur.SymulacjaPlik.czySymulacjaZakonczona.
int proj.selekcjanatur.SymulacjaPlik.index
Aktualny indeks przetwarzanego zdarzenia.
Referenced by proj.selekcjanatur.SymulacjaPlik.aktualizuj, proj.selekcjanatur.SymulacjaPlik.czySymulacjaZakonczona.
final List<Czlowiek> proj.selekcjanatur.SymulacjaPlik.ludzie
Lista ludzi w odtwarzanej symulacji.
Referenced by proj.selekcjanatur.SymulacjaPlik.aktualizuj, proj.selekcjanatur.SymulacjaPlik.dodajCzlowieka, proj.selekcjanatur.SymulacjaPlik.dodajCzlowieka, proj.selekcjanatur.SymulacjaPlik.getLudzie, proj.selekcjanatur.SymulacjaPlik.przemiescCzlowieka, proj.selekcjanatur.SymulacjaPlik.usunCzlowieka.
final Set<Jedzenie> proj.selekcjanatur.SymulacjaPlik.jedzenie
Zbiór jedzenia w odtwarzanej symulacji.
Referenced by proj.selekcjanatur.SymulacjaPlik.aktualizuj, proj.selekcjanatur.SymulacjaPlik.getJedzenie, proj.selekcjanatur.SymulacjaPlik.usunJedzenie.
proj.selekcjanatur.SymulacjaPlik.SymulacjaPlik(String nazwaPliku)
Konstruktor wczytujący dziennik zdarzeń z pliku.
nazwaPliku Ścieżka do pliku dziennika zdarzeń IOException Jeśli wystąpi błąd odczytu pliku
void proj.selekcjanatur.SymulacjaPlik.aktualizuj()
Aktualizuje stan symulacji o jeden krok.
Przetwarza kolejne zdarzenia z dziennika aż do napotkania zdarzenia KLATKA, które oznacza koniec aktualnej klatki symulacji.
References proj.selekcjanatur.SymulacjaPlik.dodajCzlowieka, proj.selekcjanatur.SymulacjaPlik.index, proj.selekcjanatur.SymulacjaPlik.jedzenie, proj.selekcjanatur.SymulacjaPlik.ludzie, proj.selekcjanatur.SymulacjaPlik.przemiescCzlowieka, proj.selekcjanatur.SymulacjaPlik.usunCzlowieka, proj.selekcjanatur.SymulacjaPlik.usunJedzenie, proj.selekcjanatur.SymulacjaPlik.zdarzenia.
boolean proj.selekcjanatur.SymulacjaPlik.czySymulacjaZakonczona()
Sprawdza czy symulacja została w pełni odtworzona.
true jeśli wszystkie zdarzenia zostały przetworzone
References proj.selekcjanatur.SymulacjaPlik.index, proj.selekcjanatur.SymulacjaPlik.zdarzenia.
List< Czlowiek > proj.selekcjanatur.SymulacjaPlik.getLudzie()
Zwraca listę ludzi w odtwarzanej symulacji.
Lista obiektów Czlowiek
References proj.selekcjanatur.SymulacjaPlik.ludzie.
Set< Jedzenie > proj.selekcjanatur.SymulacjaPlik.getJedzenie()
Zwraca zbiór jedzenia w odtwarzanej symulacji.
Zbiór obiektów Jedzenie
References proj.selekcjanatur.SymulacjaPlik.jedzenie.
void proj.selekcjanatur.SymulacjaPlik.dodajCzlowieka(String[] dane)
Dodaje człowieka na podstawie danych z dziennika.
dane Tablica parametrów zdarzenia DODANIE_CZLOWIEKA
References proj.selekcjanatur.SymulacjaPlik.ludzie.
Referenced by proj.selekcjanatur.SymulacjaPlik.aktualizuj.
void proj.selekcjanatur.SymulacjaPlik.dodajCzlowieka(String czyM, String xStr, String yStr)
Dodaje dziecko powstałe w wyniku rozmnożenia.
czyM Płeć dziecka (true = mężczyzna) xStr Pozycja x dziecka yStr Pozycja y dziecka
References proj.selekcjanatur.SymulacjaPlik.ludzie.
void proj.selekcjanatur.SymulacjaPlik.przemiescCzlowieka(String[] dane)
Przenosi człowieka na nową pozycję
dane Tablica parametrów zdarzenia PRZEMIESZCZENIE
References proj.selekcjanatur.SymulacjaPlik.ludzie.
Referenced by proj.selekcjanatur.SymulacjaPlik.aktualizuj.
void proj.selekcjanatur.SymulacjaPlik.usunJedzenie(String[] dane)
Usuwa zjedzone jedzenie.
dane Tablica parametrów zdarzenia ZJEDZONO
References proj.selekcjanatur.SymulacjaPlik.jedzenie.
Referenced by proj.selekcjanatur.SymulacjaPlik.aktualizuj.
void proj.selekcjanatur.SymulacjaPlik.usunCzlowieka(String[] dane)
Usuwa martwego człowieka.
dane Tablica parametrów zdarzenia SMIERC
References proj.selekcjanatur.SymulacjaPlik.ludzie.
Referenced by proj.selekcjanatur.SymulacjaPlik.aktualizuj.