proj::selekcjanatur::Symulacja
int proj.selekcjanatur.Symulacja.szerokosc
Statyczne parametry symulacji - szerokość planszy.
Referenced by proj.selekcjanatur.StartController.replayFromFile, proj.selekcjanatur.Symulacja.ustawParametry.
int proj.selekcjanatur.Symulacja.wysokosc
Statyczne parametry symulacji - wysokość planszy.
Referenced by proj.selekcjanatur.StartController.replayFromFile, proj.selekcjanatur.Symulacja.ustawParametry.
int proj.selekcjanatur.Symulacja.liczbaLudzi
Statyczne parametry symulacji - początkowa liczba ludzi.
Referenced by proj.selekcjanatur.Symulacja.Symulacja, proj.selekcjanatur.Symulacja.ustawParametry.
int proj.selekcjanatur.Symulacja.poczatkoweJedzenie
Statyczne parametry symulacji - początkowa ilość jedzenia.
Referenced by proj.selekcjanatur.Symulacja.Symulacja, proj.selekcjanatur.Symulacja.ustawParametry.
int proj.selekcjanatur.Symulacja.jedzenieNaTick
Statyczne parametry symulacji - nowe jedzenie na cykl.
Referenced by proj.selekcjanatur.Symulacja.aktualizujStan, proj.selekcjanatur.Symulacja.ustawParametry.
final int proj.selekcjanatur.Symulacja.kolumny
Liczba kolumn planszy (szerokość)
Referenced by proj.selekcjanatur.Symulacja.dodajLosoweJedzenie, proj.selekcjanatur.Symulacja.dodajLosowychLudzi, proj.selekcjanatur.Symulacja.Symulacja, proj.selekcjanatur.Symulacja.wykonajRuch.
final int proj.selekcjanatur.Symulacja.wiersze
Liczba wierszy planszy (wysokość)
Referenced by proj.selekcjanatur.Symulacja.dodajLosoweJedzenie, proj.selekcjanatur.Symulacja.dodajLosowychLudzi, proj.selekcjanatur.Symulacja.Symulacja, proj.selekcjanatur.Symulacja.wykonajRuch.
final List<Czlowiek> proj.selekcjanatur.Symulacja.ludzie
Lista wszystkich ludzi w symulacji.
Referenced by proj.selekcjanatur.Symulacja.aktualizuj, proj.selekcjanatur.Symulacja.aktualizujStan, proj.selekcjanatur.Symulacja.czySymulacjaZakonczena, proj.selekcjanatur.Symulacja.dodajLosowychLudzi, proj.selekcjanatur.Symulacja.getLudzie, proj.selekcjanatur.Symulacja.znajdzPartnera.
final Set<Jedzenie> proj.selekcjanatur.Symulacja.jedzenie
Zbiór dostępnego jedzenia na planszy.
Referenced by proj.selekcjanatur.Symulacja.dodajLosoweJedzenie, proj.selekcjanatur.Symulacja.getJedzenie, proj.selekcjanatur.Symulacja.przemiescSieNaPole, proj.selekcjanatur.Symulacja.wykonajRuch, proj.selekcjanatur.Symulacja.znajdzJedzenieNaPolu, proj.selekcjanatur.Symulacja.znajdzNajblizszeJedzenie.
int proj.selekcjanatur.Symulacja.licznikKlatek
Licznik klatek symulacji.
Referenced by proj.selekcjanatur.Symulacja.aktualizuj.
int proj.selekcjanatur.Symulacja.licznikDodawaniaJedzenia
Licznik kontrolujący dodawanie nowego jedzenia.
Referenced by proj.selekcjanatur.Symulacja.aktualizujStan.
final boolean [][] proj.selekcjanatur.Symulacja.zajete
Mapa zajętości pól na planszy.
Referenced by proj.selekcjanatur.Symulacja.aktualizujStan, proj.selekcjanatur.Symulacja.dodajLosowychLudzi, proj.selekcjanatur.Symulacja.przemiescSieNaPole, proj.selekcjanatur.Symulacja.wykonajRuch.
final List<String> proj.selekcjanatur.Symulacja.dziennikZdarzen
Dziennik zdarzeń zapisywany do pliku.
Referenced by proj.selekcjanatur.Symulacja.dodajDoDziennika, proj.selekcjanatur.Symulacja.zapiszDziennikDoPliku.
final List<int[]> proj.selekcjanatur.Symulacja.KIERUNKI
Lista możliwych kierunków ruchu.
Referenced by proj.selekcjanatur.Symulacja.wykonajRuch.
static void proj.selekcjanatur.Symulacja.ustawParametry(int w, int h, int l, int j, int jt)
Ustawia globalne parametry symulacji.
w Szerokość planszy h Wysokość planszy l Początkowa liczba ludzi j Początkowa ilość jedzenia jt Ilość nowego jedzenia dodawanego co cykl
References proj.selekcjanatur.Symulacja.jedzenieNaTick, proj.selekcjanatur.Symulacja.liczbaLudzi, proj.selekcjanatur.Symulacja.poczatkoweJedzenie, proj.selekcjanatur.Symulacja.szerokosc, proj.selekcjanatur.Symulacja.wysokosc.
Referenced by proj.selekcjanatur.StartController.startSimulation.
static void proj.selekcjanatur.Symulacja.zapiszDziennikDoPliku(String nazwaPliku)
Zapisuje dziennik zdarzeń do pliku.
nazwaPliku Nazwa pliku do zapisu
References proj.selekcjanatur.Symulacja.dziennikZdarzen.
Referenced by proj.selekcjanatur.App.main, proj.selekcjanatur.AppController.pokazOknoZakonczenia.
proj.selekcjanatur.Symulacja.Symulacja(int kolumny, int wiersze)
Konstruktor inicjalizujący symulację
kolumny Szerokość planszy wiersze Wysokość planszy
References proj.selekcjanatur.Symulacja.dodajDoDziennika, proj.selekcjanatur.Symulacja.dodajLosoweJedzenie, proj.selekcjanatur.Symulacja.dodajLosowychLudzi, proj.selekcjanatur.Symulacja.kolumny, proj.selekcjanatur.Symulacja.liczbaLudzi, proj.selekcjanatur.Symulacja.poczatkoweJedzenie, proj.selekcjanatur.Symulacja.wiersze.
List< Czlowiek > proj.selekcjanatur.Symulacja.getLudzie()
Zwraca listę ludzi w symulacji.
Lista obiektów Czlowiek
References proj.selekcjanatur.Symulacja.ludzie.
Set< Jedzenie > proj.selekcjanatur.Symulacja.getJedzenie()
Zwraca zbiór jedzenia w symulacji.
Zbiór obiektów Jedzenie
References proj.selekcjanatur.Symulacja.jedzenie.
void proj.selekcjanatur.Symulacja.aktualizuj()
Aktualizuje stan symulacji o jeden krok.
Wykonuje: Aktualizację stanu co 3 klatki Ruch ludzi zgodnie z ich predyspozycjami Dodawanie nowego jedzenia Rozmnażanie i usuwanie martwych
References proj.selekcjanatur.Symulacja.aktualizujStan, proj.selekcjanatur.Symulacja.dodajDoDziennika, proj.selekcjanatur.Symulacja.licznikKlatek, proj.selekcjanatur.Symulacja.ludzie, proj.selekcjanatur.Symulacja.wykonajRuch.
boolean proj.selekcjanatur.Symulacja.czySymulacjaZakonczena()
Sprawdza czy symulacja powinna się zakończyć
true jeśli nie ma żywych ludzi
References proj.selekcjanatur.Symulacja.ludzie.
void proj.selekcjanatur.Symulacja.dodajDoDziennika(String zdarzenie)
Dodaje wpis do dziennika zdarzeń
zdarzenie Tekstowy opis zdarzenia
References proj.selekcjanatur.Symulacja.dziennikZdarzen.
Referenced by proj.selekcjanatur.Symulacja.aktualizuj, proj.selekcjanatur.Symulacja.aktualizujStan, proj.selekcjanatur.Symulacja.dodajLosoweJedzenie, proj.selekcjanatur.Symulacja.dodajLosowychLudzi, proj.selekcjanatur.Symulacja.przemiescSieNaPole, proj.selekcjanatur.Symulacja.Symulacja.
void proj.selekcjanatur.Symulacja.dodajLosowychLudzi(int ile)
Dodaje losowych ludzi na planszę
ile Liczba ludzi do dodania
References proj.selekcjanatur.Czlowiek.czyMezczyzna, proj.selekcjanatur.Symulacja.dodajDoDziennika, proj.selekcjanatur.Symulacja.kolumny, proj.selekcjanatur.Symulacja.ludzie, proj.selekcjanatur.App.random, proj.selekcjanatur.Czlowiek.wiek, proj.selekcjanatur.Symulacja.wiersze, proj.selekcjanatur.Czlowiek.x, proj.selekcjanatur.Czlowiek.y, proj.selekcjanatur.Symulacja.zajete.
Referenced by proj.selekcjanatur.Symulacja.Symulacja.
void proj.selekcjanatur.Symulacja.dodajLosoweJedzenie(int ile)
Dodaje losowe jedzenie na planszę
ile Liczba jedzenia do dodania
References proj.selekcjanatur.Symulacja.dodajDoDziennika, proj.selekcjanatur.Symulacja.jedzenie, proj.selekcjanatur.Symulacja.kolumny, proj.selekcjanatur.App.random, proj.selekcjanatur.Symulacja.wiersze.
Referenced by proj.selekcjanatur.Symulacja.aktualizujStan, proj.selekcjanatur.Symulacja.Symulacja.
void proj.selekcjanatur.Symulacja.aktualizujStan()
Aktualizuje stan symulacji (co 3 klatki)
Wykonuje: Dodawanie nowego jedzenia Aktualizację stanu ludzi Rozmnażanie i usuwanie martwych
References proj.selekcjanatur.Czlowiek.czyMezczyzna, proj.selekcjanatur.Symulacja.dodajDoDziennika, proj.selekcjanatur.Symulacja.dodajLosoweJedzenie, proj.selekcjanatur.Symulacja.jedzenieNaTick, proj.selekcjanatur.Symulacja.licznikDodawaniaJedzenia, proj.selekcjanatur.Symulacja.ludzie, proj.selekcjanatur.Czlowiek.mozeRozmnazac, proj.selekcjanatur.Czlowiek.rozmnazajZ, proj.selekcjanatur.Czlowiek.wiek, proj.selekcjanatur.Czlowiek.x, proj.selekcjanatur.Czlowiek.y, proj.selekcjanatur.Symulacja.zajete, proj.selekcjanatur.Czlowiek.zywy.
Referenced by proj.selekcjanatur.Symulacja.aktualizuj.
void proj.selekcjanatur.Symulacja.wykonajRuch(Czlowiek cz)
Wykonuje ruch dla danego człowieka.
cz Człowiek, który ma się poruszyć
References proj.selekcjanatur.Symulacja.jedzenie, proj.selekcjanatur.Symulacja.KIERUNKI, proj.selekcjanatur.Symulacja.kolumny, proj.selekcjanatur.Symulacja.przemiescSieNaPole, proj.selekcjanatur.Symulacja.wiersze, proj.selekcjanatur.Czlowiek.x, proj.selekcjanatur.Czlowiek.y, proj.selekcjanatur.Symulacja.zajete, proj.selekcjanatur.Symulacja.znajdzNajblizszeJedzenie, proj.selekcjanatur.Symulacja.znajdzPartnera.
Referenced by proj.selekcjanatur.Symulacja.aktualizuj.
Czlowiek proj.selekcjanatur.Symulacja.znajdzPartnera(Czlowiek cz)
Znajduje partnera do rozmnażania w zasięgu wzroku.
cz Człowiek szukający partnera Znaleziony partner lub null
References proj.selekcjanatur.Czlowiek.czyMezczyzna, proj.selekcjanatur.Symulacja.ludzie, proj.selekcjanatur.Czlowiek.x, proj.selekcjanatur.Czlowiek.y, proj.selekcjanatur.Czlowiek.zasiegWzroku, proj.selekcjanatur.Czlowiek.zywy.
Referenced by proj.selekcjanatur.Symulacja.wykonajRuch.
Jedzenie proj.selekcjanatur.Symulacja.znajdzNajblizszeJedzenie(Czlowiek cz)
Znajduje najbliższe jedzenie w zasięgu wzroku.
cz Człowiek szukający jedzenia Znalezione jedzenie lub null
References proj.selekcjanatur.Symulacja.jedzenie, proj.selekcjanatur.Czlowiek.x, proj.selekcjanatur.Czlowiek.y, proj.selekcjanatur.Czlowiek.zasiegWzroku.
Referenced by proj.selekcjanatur.Symulacja.wykonajRuch.
Jedzenie proj.selekcjanatur.Symulacja.znajdzJedzenieNaPolu(int x, int y)
Sprawdza czy na danym polu jest jedzenie.
x Pozycja x y Pozycja y Obiekt jedzenia lub null
References proj.selekcjanatur.Symulacja.jedzenie.
Referenced by proj.selekcjanatur.Symulacja.przemiescSieNaPole.
void proj.selekcjanatur.Symulacja.przemiescSieNaPole(Czlowiek cz, int x, int y)
Przenosi człowieka na nowe pole.
cz Człowiek do przeniesienia x Nowa pozycja x y Nowa pozycja y
References proj.selekcjanatur.Symulacja.dodajDoDziennika, proj.selekcjanatur.Symulacja.jedzenie, proj.selekcjanatur.Czlowiek.x, proj.selekcjanatur.Czlowiek.y, proj.selekcjanatur.Symulacja.zajete, proj.selekcjanatur.Czlowiek.zjedz, proj.selekcjanatur.Symulacja.znajdzJedzenieNaPolu.
Referenced by proj.selekcjanatur.Symulacja.wykonajRuch.